# Generated by Django 5.0.6 on 2025-04-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_qshistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='qshistory',
            name='qid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
